// src/constants/auth-types.js

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const LOGOUT_ATTEMPT = 'LOGOUT_ATTEMPT';

export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';

export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';

export const REGISTRATION_ATTEMPT = 'REGISTRATION_ATTEMPT';