

export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';

export const CREATE_QUESTION_ERROR = 'CREATE_QUESTION_ERROR';

export const DESTROY_QUESTION_SUCCESS = 'DESTROY_QUESTION_SUCCESS'

export const DESTROY_QUESTION_ERROR = 'DESTROY_QUESTION_ERROR'